import './globals.scss'
import { Inter } from 'next/font/google'
import { LanguageProv } from "@/contexts/LanguageContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'CIAC Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <LanguageProv>
        <body className={inter.className}>{children}</body>
      </LanguageProv>
    </html>
  )
}
